### ISSUE TITLE
Unable to retrieve JSON from Azure blob storage

### ISSUE THREAD

**Issue by jd-rs** [orcasound/aifororcas-podcast#1]
When running the annotation system app, I get this message from Chrome.
![unable-to-retreive-json](https://user-images.githubusercontent.com/54477758/84524963-71127000-aca0-11ea-8592-5ba4026216d1.png)

**Comment by akashmjn** [comment]
@jd-r this was happening because you didn't have the right Azure blob credentials. (see the docs in the README to see how it's architected). 

This V1.0 release should fix and make a lot of things clearer. I'll DM you a YAML file to try with a blob account that's already setup. Closing this issue.
